# Imagen oficial de PostgreSQL
FROM postgres:16

# Variables de entorno para la BD
ENV POSTGRES_USER=scena_user
ENV POSTGRES_PASSWORD=scena_pass
ENV POSTGRES_DB=scena_db

# Exponemos el puerto por defecto
EXPOSE 5432
